;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="MapGeneration.Spawned",NewTagName="MapGeneration.PathStart")
+GameplayTagRedirects=(OldTagName="MapGeneration.Regions.Watera",NewTagName="MapGeneration.Regions.Water")
+GameplayTagList=(Tag="MapGeneration.Initialised",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Landscape",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Path",DevComment="")
+GameplayTagList=(Tag="MapGeneration.PathStart",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Regions.Ice",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Regions.Lava",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Regions.Moss",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Regions.Rock",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Regions.Water",DevComment="")

