;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="MapGeneration.Spawned",NewTagName="MapGeneration.PathStart")
+GameplayTagList=(Tag="MapGeneration.Initialised",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Landscape",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Landscape.Ice",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Landscape.Lava",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Landscape.Moss",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Landscape.Rock",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Landscape.Water",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Path",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Path.Ice",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Path.Lava",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Path.Moss",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Path.Rock",DevComment="")
+GameplayTagList=(Tag="MapGeneration.Path.Water",DevComment="")
+GameplayTagList=(Tag="MapGeneration.PathStart",DevComment="")

